### ISSUE TITLE
Subwasm diff bug

### ISSUE THREAD

**Issue by sacha-l** [chevdor/subwasm#32]
Trying to do a diff between two wasm files. Rust is panicking - full logs with RUST_BACKTRACE=full below.

Steps:

1. `subwasm get --chain polkadot --block 0xfdeab19649426aadbdab046c9b5dac0a5b0c850b8fd0927e3b4e6c896d5fb0b7 -o polkadot-50000.wasm`
2. `subwasm get --chain polkadot -o polkadot-latest.wasm`
3. `subwasm diff polkadot-latest.wasm polkadot-50000.wasm`

```bash
Running subwasm v0.16.1
[2021-11-10T20:54:47Z DEBUG subwasmlib] Loading WASM runtimes:
  🅰️  File("polkadot-50000.wasm")
thread 'main' panicked at 'Can only diff if the 2 runtimes can load: Decoding([109, 101, 116, 97, 11, 124, 24, 83, 121, 115, 116, 101, 109, 1, 24, 83, 121, 115, 116, 101, 109, 60, 28, 65, 99, 99, 111, 117, 110, 116, 1, 1, 2, 48, 84, 58, 58, 65, 99, 99, 111, 117, 110, 116, 73, 100, 148, 65, 99, 99, 111, 117, 110, 116, 73, 110, 102, 111, 60, 84, 58, 58, 73, 110, 100, 101, 120, 44, 32, 84, 58, 58, 65, 99, 99, 111, 117, 110, 116, 68, 97, 116, 97, 62, 0, 21, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])', lib/src/lib.rs:113:46
stack backtrace:
   0:        0x102bb2224 - std::backtrace_rs::backtrace::libunwind::trace::h3788418f13e49f6e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x102bb2224 - std::backtrace_rs::backtrace::trace_unsynchronized::hf189cd7ee07b4d2b
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102bb2224 - std::sys_common::backtrace::_print_fmt::hcd10aea219dfc188
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x102bb2224 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha9fb0042c142196e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x102bcceac - core::fmt::write::ha61991bf8ecf136a
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:        0x102bac094 - std::io::Write::write_fmt::h46c2e7b09a3411d3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:        0x102bb3a4c - std::sys_common::backtrace::_print::h66fb61bcb7af7f3c
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x102bb3a4c - std::sys_common::backtrace::print::hd77bcd12ac793f65
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x102bb3a4c - std::panicking::default_hook::{{closure}}::h2e75467530bdcca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:        0x102bb3618 - std::panicking::default_hook::habe288fd56f5750a
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:        0x102bb408c - std::panicking::rust_panic_with_hook::h0de8caef2b5cd059
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:        0x102bb3bd8 - std::panicking::begin_panic_handler::{{closure}}::hacf45a4761576516
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
  12:        0x102bb26fc - std::sys_common::backtrace::__rust_end_short_backtrace::hc8935facac9e6044
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x102bb3b40 - rust_begin_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  14:        0x102bf2e7c - core::panicking::panic_fmt::h976396c8435074ae
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
  15:        0x102bf2f20 - core::result::unwrap_failed::h0f27636d1d025391
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
  16:        0x10267cba0 - subwasmlib::diff::h6980073a3c78769b
  17:        0x102649154 - subwasm::main::ha34726a4b433bbb9
  18:        0x102646c10 - std::sys_common::backtrace::__rust_begin_short_backtrace::h241cfdc5d2773249
  19:        0x102650028 - std::rt::lang_start::{{closure}}::h811c5a14b3843340
  20:        0x102bb4504 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h51c1d4e6d77bdcbb
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  21:        0x102bb4504 - std::panicking::try::do_call::h89fe052533bafbda
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  22:        0x102bb4504 - std::panicking::try::h46d7f0e49ad79887
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  23:        0x102bb4504 - std::panic::catch_unwind::h39132fca9d95ef81
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  24:        0x102bb4504 - std::rt::lang_start_internal::{{closure}}::h6539b3c59dc74c9d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  25:        0x102bb4504 - std::panicking::try::do_call::h5b104bf56577bb16
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  26:        0x102bb4504 - std::panicking::try::h7769cac6f81ef323
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  27:        0x102bb4504 - std::panic::catch_unwind::h3b24c77fb952102f
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  28:        0x102bb4504 - std::rt::lang_start_internal::hb4d1fe995f6e94ee
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  29:        0x102649528 - _main
```

**Comment by chevdor** [comment]
Could you please attach this runtime to the issue ?

**Comment by sacha-l** [comment]
Not sure what you mean - this is for the Polkadot runtime as specified in the tool. I'm unable to attach a `.wasm` file here unfortunately.

**Comment by sacha-l** [comment]
Follow-up PR: #33
